## Introduction

Working with numbers is central to almost all scientific and engineering computations.
The topic is so important that there are many dedicated libraries to help implement efficient numerical
computations. There are even languages that are specifically designed for numerical computation, such as Fortran
and MATLAB.

NumPy (http://www.numpy.org/) is the most widely used Python library for numerical computations. It provides an extensive range of data structures and functions for numerical
computation. In this notebook we will explore just some of the functionality.
You will be seeing NumPy in other courses. NumPy can perform many of the operations that you will learn
during the mathematics courses.

Another library, which largely builds on NumPy and provides additional functionality, is SciPy (https://www.scipy.org/). SciPy provides some more specialised data structures and functions over NumPy.
If you are familiar with MATLAB, NumPy and SciPy provide much of what is available in MATLAB.

NumPy is a large and extensive library and this activity is just a very brief introduction.
To discover how to perform operations with NumPy, your best resources are search engines, such as http://stackoverflow.com/.

### Objectives

- Introduction to 1D and 2D arrays (vector and matrices)
- Manipulating arrays (indexing, slicing, etc)
- Apply elementary numerical operations
- Demonstrate efficiency differences between vectorised and non-vectorised functions

## 介绍

数值运算是几乎所有科学和工程计算的核心。本主题非常重要，有许多专用库可帮助实现有效的数值计算。甚至还有专为数值计算而设计的语言，例如 Fortran 和 MATLAB。

NumPy（http://www.numpy.org/ ）是用于数值计算的最广泛使用的 Python 库。它为数值计算提供了广泛的数据结构和函数。在这个笔记本中，我们将探讨一些功能。您将在其他课程中看到 NumPy。NumPy 可以执行您在数学课程中学到的许多操作。

另一个主要基于 NumPy 构建并提供其他功能的库是 SciPy（https://www.scipy.org/ ）。SciPy 在 NumPy 上提供了一些更专业的数据结构和功能。如果您熟悉 MATLAB，NumPy 和 SciPy 提供了 MATLAB 中可用的大部分内容。

NumPy 是一个庞大而广泛的库，这里只是一个非常简短的介绍。要了解如何使用 NumPy 执行操作，您的最佳资源是搜索引擎，例如 <http://stackoverflow.com/>。

### 目标

- 一维和二维数组（矢量和矩阵）简介
- 操作数组（索引，切片等）
- 应用基本数值运算
- 展示矢量化和非矢量化函数之间的效率差异

## Importing the NumPy module

To make NumPy available in our programs, we need to import the module. It has become an informal custom to import NumPy using the shortcut '`np`':

## 导入 NumPy 模块

要在我们的程序中使用 NumPy，我们需要导入该模块。将导入的 NumPy 缩写为'`np`' 已经成为一种非正式的习惯：

In [1]:
import numpy as np

## Numerical arrays

We have already seen Python 'lists', which hold 'arrays' of data. We can access the elements of a list using an index because the entries are stored in order. Python lists are very flexible and can hold mixed data types, e.g. combinations of floats and strings, or even lists of lists of lists . . .

The flexibility of Python lists comes at the expense of performance. Many science, engineering and mathematics problems involve very large problems with operations on numbers, and computational speed is important for large problems. To serve this need, we normally use specialised functions and data structures for numerical computation, and in particular for arrays of numbers. Some of the flexibility of lists is traded for performance.

## 数组

我们已经看到了 Python'列表'，它们包含数据的 “阵列”。我们可以使用索引访问列表的元素，因为条目按顺序存储。Python 列表非常灵活，可以保存混合数据类型，例如 浮点数和字符串的组合，甚至列表的列表。。。

Python 列表的灵活性是以牺牲性能为代价的。许多科学，工程和数学问题涉及非常大量的数学运算问题，而计算速度对于大问题是重要的。为了满足这种需要，我们通常使用专门的函数和数据结构进行数值计算，特别是数字数组。列表用降低性能换取了一些灵活性。

### One-dimensional arrays

A one-dimensional array is a collection of numbers which we can access by index (it preserves order).

### 一维数组

一维数组是我们可以通过索引访问的数字集合（它保留了顺序）。

<font size=4 weight=600 >Creating arrays and indexing</font>

To create a NumPy array of length 10 and initially filled with zeros:

<font size=4 weight=600 >创建数组和索引</font>

要创建长度为 10 且用零为初始值填充的 NumPy 数组：

In [2]:
x = np.zeros(10)

print(x)
print(type(x))

The default type of a NumPy array is`float`. The type can be checked with

Numpy 数组的默认类型是 `float`。可以通过如下方式检验类型：

In [3]:
print(x.dtype)

You cannot, for example, add a`string`to a`numpy.ndarray`. All entries in the array have the same type.

We can check the length of an array using`len`, which gives the number of entries in the array:

例如，你不能将 `string` 添加到 `numpy.ndarray` 中。数组中的所有条目都具有相同的类型。

我们可以使用 `len` 来检查数组的长度，它给出了数组中的条目数：

In [4]:
print(len(x))

A better way to check the length is to use`x.shape`, which returns a tuple with the dimensions of the array:

检查长度的更好方法是使用 `x.shape`，它返回一个具有数组维度的元组：

In [5]:
print(x.shape)

`shape`tells us the size of the array in *each* direction. We will see two-dimensional arrays shortly (matrices), which have a size in each direction.

`shape` 告诉我们*每个*方向上数组的大小。我们将马上看到的二维数组（矩阵），每个方向都有大小。

We can change the entries of an array using indexing,

我们可以使用索引来更改数组的条目，

In [6]:
print(x)

x[0] = 10.0
x[3] = -4.3
x[9] = 1.0

print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[10.   0.   0.  -4.3  0.   0.   0.   0.   0.   1. ]


Remember that indexing starts from zero!
There are other ways to create arrays, such as an array of 'ones':

请记住，索引从零开始！

还有其他方法可以创建数组，例如'ones'数组：

In [7]:
y = np.ones(5)
print(y)

[1. 1. 1. 1. 1.]


an array of random values:

一个随机数组

In [8]:
y = np.random.rand(6)
print(y)

[0.60861561 0.6364807  0.27694109 0.68383925 0.76173909 0.56105644]


or a NumPy array from a Python list:

或者从 Python 列表建立一个 Numpy 数组：

In [9]:
x = [4.0, 8.0, 9.0, 11.0, -2.0]
y = np.array(x)
print(y)

[ 4.  8.  9. 11. -2.]


Two more methods for creating arrays which we will use in later notebooks are:

-`numpy.arange`; and
-`numpy.linspace`.

They are particularly useful for plotting functions.
The function`arange`creates an array with equally spaced values. It is similar in some cases to`range`, which we have seen earlier. To create the array`[0 1 2 3 4 5]`using`arange`:

我们将在以后的笔记本中使用的另外两种创建数组的方法是：

-`numpy.arange`; and
-`numpy.linspace`.

它们对绘制函数特别有用。
函数 `arange` 创建一个具有等间距值的数组。它在某些情况下类似于我们之前已经看到过 `range`。使用 `arange` 创建数组 `[0 1 2 3 4 5]`：

In [10]:
x = np.arange(6)
print(x)
print(type(x))

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


Note that '6' is not included. We can change the start value, e.g.:

注意'6'不包括在内。我们可以更改起始值，例如：

In [11]:
x = np.arange(2, 6)
print(x)

[2 3 4 5]


The function`linspace`creates an array with prescribed start and end values (both are included), and a prescribed number on values, all equally spaced:

函数 `linspace` 创建一个数组，其中包含规定的起始值和结束值（两者都包含在内），以及两者之间等间隔的数字。

In [12]:
x = np.linspace(0, 100, 6)
print(x)

[  0.  20.  40.  60.  80. 100.]


The`linspace`function is used extensively for plotting, as we will see in the next notebook.

`linspace` 函数广泛用于绘图，我们将在下一个笔记本中看到。


**XUE.cn 练习题**：

- [选择题 ★★★ numpy 数组的 ndim 属性](https://xue.cn/hub/app/exercise/312)

- [选择题 ★★★ numpy 数组的 size 属性](https://xue.cn/hub/app/exercise/313)

- [选择题 ★★★ numpy 库的 zeros 和 ones 函数](https://xue.cn/hub/app/exercise/314)

- [选择题 ★★★ numpy 库的 arange 函数](https://xue.cn/hub/app/exercise/315)

<font size=4 weight=600 >Array arithmetic and functions</font>

NumPy arrays support common arithmetic operations, such as addition of two arrays

<font size=4 weight=600 >数组算术和函数</font>

NumPy 数组支持常见的算术运算，例如两个数组的加法

In [13]:
x = np.array([1.0, 0.2, 1.2])
y = np.array([2.0, 0.1, 2.1])
print(x)
print(y)

## Sum x and y
z = x + y
print(z)

[1.  0.2 1.2]
[2.  0.1 2.1]
[3.  0.3 3.3]


and multiplication of components by a scalar,

矩阵与标量的乘法

In [14]:
z = 10.0*x
print(z)

[10.  2. 12.]


and raising components to a power:

矩阵元素的乘方

In [15]:
x = np.array([2, 3, 4])
print(x**2)

[ 4  9 16]


**XUE.cn 练习题**：

- [选择题 ★★★ numpy 数组的广播计算 1](https://xue.cn/hub/app/exercise/310)

- [选择题 ★★★ numpy 数组的广播计算 2](https://xue.cn/hub/app/exercise/311)

- [选择题 ★★★ numpy 数组不同形状不能广播计算](https://xue.cn/hub/app/exercise/316)

- [选择题 ★★★ numpy 数组的计算](https://xue.cn/hub/app/exercise/317)

We can also apply functions to the components of an array:

我们还可以将函数应用于数组的元素：

In [16]:
## Create an array [0, π/2, π, 3π/2]
x = np.array([0.0, np.pi/2, np.pi, 3*np.pi/2])
print(x)

## Compute sine of each entry
y = np.sin(x)
print(y)

[0.         1.57079633 3.14159265 4.71238898]
[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]


The above has computed the sine of each entry in the array`x`.

Note that the function`np.sin`is used, and not`math.sin`(which was used in previous notebooks). The reason is that`np.sin`is more general - it can act on lists/arrays of values rather than on just one value. We will apply functions to arrays in the next notebook to plot functions.

上面已经计算了数组 `x` 中每个元素的正弦值。

请注意，使用了函数 `np.sin`，而不是 `math.sin`（在以前的笔记本中使用过）。原因是 `np.sin` 更通用 - 它可以作用于列表 / 数组元素而不是仅仅作用于一个值。我们将函数应用于下一个笔记本中的数组以绘制函数。

We could have computed the sine of each array entry using`for`loops:

我们可以使用 `for` 循环计算每个数组条目的正弦值：

In [17]:
y = np.zeros(len(x))
for i in range(len(x)):
    y[i] = np.sin(x[i])

print(y)

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]


but the program becomes longer and harder to read. Additionally, in many cases it will be much slower.
You might see manipulation of arrays without indexing referred to as 'vectorisation'. When possible, vectorisation is a good thing to do. We compare the performance of indexing versus vectorisation below.

但程序变得越来越难以阅读。此外，在许多情况下，它会慢得多。
您可能会看到没有索引的数组操作，称为 “矢量化”。在可能的情况下，矢量化是一件好事。我们比较下面的索引与矢量化的性能。

<font size=4 weight=600 >Performance example: computing the norm of a long vector</font>

The norm of a vector $x$ is given by:

$$
\| x \| = \sqrt{\sum_{i=0}^{n-1} x_{i} x_{i}}
$$

where $x_{i}$ is the $i$th entry of $x$. It is the dot product of a vector with itself,
followed by taking the square root.
To compute the norm, we could loop/iterate over the entries of the vector and sum the square of each entry, and then take the square root of the result.

We will evaluate the norm using two methods for computing the norm of an array of length 10 million to compare their performance. We first create a vector with 10 million random entries, using NumPy:

<font size=4 weight=600 >性能示例：计算长向量的范数</font>

向量$x$ 的范数（此处计算的是二阶范数，也就是向量的长度）由下式给出：

$$
\| x \| = \sqrt{\sum_{i=0}^{n-1} x_{i} x_{i}}
$$

其中 $x_{i}$是$x$的第$i$元素。它是矢量与自身的点积，然后取平方根。
为了计算范数，我们可以循环 / 迭代向量的条目并对每个条目的平方求和，然后取结果的平方根。

我们将使用两种方法来评估，以计算长度为 1000 万的数组的范数，以比较它们的性能。我们首先使用 NumPy 创建一个包含 1000 万个随机条目的向量：

In [18]:
## Create a NumPy array with 10 million random values
x = np.random.rand(10000000)
print(type(x))

<class 'numpy.ndarray'>


We now time how long it takes to compute the norm of the vector using the NumPy function '`numpy.dot`'. We use the Jupyter 'magic command' [`%time`](Notebook_tips.ipynb#Simple-timing) to time the operation:

我们现在计算使用 NumPy 函数'`numpy.dot`'来计算向量范数需要多长时间。我们使用 Jupyter'魔术命令 [`%time`](Notebook_tips.ipynb#Simple-timing) 来为操作计时：

In [19]:
%time norm = np.sqrt(np.dot(x, x))
print(norm)

CPU times: user 6.34 ms, sys: 0 ns, total: 6.34 ms
Wall time: 5.34 ms
1825.4805730455523


The time output of interest is '`Wall time`'.

> The details of how`%time`works are not important for this course. We use it as a compact and covenient tool to
> measure how much time a command takes to execute.

We now perform the same operation with our own function for computing the norm:

我们感兴趣的时间是 “Wall time”。

> “％time” 如何运作的细节对于本课程并不重要。我们将它用作一个紧凑而便捷的工具来衡量命令执行的时间。

我们现在使用我们自己的函数执行相同的操作来计算范数：

In [20]:
def compute_norm(x):
    norm = 0.0
    for xi in x:
        norm += xi*xi
    return np.sqrt(norm)

%time norm =compute_norm(x)
print(norm)

CPU times: user 1.15 s, sys: 2.24 ms, total: 1.15 s
Wall time: 1.15 s
1825.480573045718


You should see that the two approaches give the same result, but the
NumPy function is more than 100 times faster, and possibly more than 100,000 times faster!

The message is that specialised functions and data structures for numerical computations can be many orders of magnitude faster than your own general implementations. On top of that, the specialised functions are much less
likely to have bugs!

您应该看到这两种方法给出相同的结果，但是
NumPy 功能的速度提高了 100 多倍，速度可能超过 100,000 倍！

这个实验传达的消息是，用于数值计算的专用函数和数据结构可以比您自己的一般实现快许多个数量级。最重要的是，专门的功能不太可能有 bug！

**XUE.cn 练习题**：

- [选择题 ★★★ numpy 数组的 sum 方法求和](https://xue.cn/hub/app/exercise/318)

- [选择题 ★★★ numpy 数组的 ravel 方法](https://xue.cn/hub/app/exercise/319)

- [编程题 ★★★ 创建长度为 10 的零向量](https://xue.cn/hub/app/exercise/1233)

- [编程题 ★★★ 获取数组所占内存大小](https://xue.cn/hub/app/exercise/1234)

- [编程题 ★★★ 怎么用命令行获取 numpy add 函数的文档说明？](https://xue.cn/hub/app/exercise/1235)

- [编程题 ★★★ 创建一个长度为 10 的零向量，并把第五个值赋值为 1](https://xue.cn/hub/app/exercise/1236)

### Two-dimensional arrays

Two-dimensional arrays are very useful for arranging data in many engineering applications and for performing mathematical operations. Commonly, 2D arrays are used to represents matrices. To create the matrix

$$
A =
\begin{bmatrix}
2.2 & 3.7 & 9.1\\
-4 & 3.1 & 1.3
\end{bmatrix}
$$

we use:

### 二维数组

二维数组对于在许多工程应用中安排数据和执行数学运算非常有用。通常，二维数组用于表示矩阵。创建矩阵

$$
A =
\begin{bmatrix}
2.2 & 3.7 & 9.1\\
-4 & 3.1 & 1.3
\end{bmatrix}
$$

我们用：

In [21]:
A = np.array([[2.2, 3.7, 9.1], [-4.0, 3.1, 1.3]])
print(A)

[[ 2.2  3.7  9.1]
 [-4.   3.1  1.3]]


If we check the length of`A`:

如果我们检查 `A` 的长度：

In [22]:
print(len(A))

2


it reports the number of rows. To get the shape of the array, we use:

它只报告了行数。为了获得数组的形状，我们使用：

In [23]:
print(A.shape)

(2, 3)


which reports 2 rows and 3 columns (stored using a tuple). To get the number of rows and the number of columns,

这次报告了 2 行 3 列（使用元组存储）。要获取行数和列数，

In [24]:
num_rows = A.shape[0]
num_cols = A.shape[1]
print("Number of rows is {}, number of columns is {}.".format(num_rows, num_cols))

Number of rows is 2, number of columns is 3.


We can 'index' into a 2D array using two indices, the first for the row index and the second for the column index:

我们可以使用两个数字来 “索引” 到 2D 数组中，第一个用于行索引，第二个用于列索引：

In [25]:
A02 = A[0, 2]
print(A02)

9.1


With`A[1]`, we will get the second row:

使用 `A [1]`，我们将获得第二行：

In [26]:
print(A[1])

[-4.   3.1  1.3]


We can iterate over the entries of`A`by iterating over the rows, and then the entry in each row:

我们可以通过迭代遍历 `A` 中的每一行，然后遍历每行中的元素：

In [27]:
for row in A:
    print("-----")
    for c in row:
        print(c)

-----
2.2
3.7
9.1
-----
-4.0
3.1
1.3


> **Warning:** NumPy has a`numpy.matrix`data structure. Its use is not recommended as it behaves inconsistently in some cases.

> **警告：** NumPy 有一个 `numpy.matrix` 数据结构。不推荐使用它，因为它在某些情况下表现不一致。

<font size=4 weight=600 >2D array (matrix) operations</font>

For those who have seen matrices previously, the operations in this section will be familiar. For those who have not encountered matrices, you might want to revisit this section once matrices have been covered in the mathematics lectures.

<font size=4 weight=600 >二维数组（矩阵）运算</font>

对于之前见过矩阵的人来说，本节中的操作还是比较熟悉的。对于那些没有遇到矩阵的人，日后数学讲座中涉及矩阵，您可能需要重新阅读本节。

<font size=4>Matrix-vector and matrix-matrix multiplication</font>

We will consider the matrix $A$:

$$
A =
\begin{bmatrix}
3.4 & 2.6 \\
2.1 & 4.5
\end{bmatrix}
$$

and the vector $x$:

$$
x =
\begin{bmatrix}
0.2 \\ -1.1
\end{bmatrix}
$$

<font size=4>矩阵与向量，矩阵与矩阵的乘法</font>

我们将考虑矩阵$A$:

$$
A =
\begin{bmatrix}
3.4 & 2.6 \\
2.1 & 4.5
\end{bmatrix}
$$

和向量 $x$:

$$
x =
\begin{bmatrix}
0.2 \\ -1.1
\end{bmatrix}
$$

In [28]:
A = np.array([[3.4, 2.6], [2.1, 4.5]])
print("Matrix A:\n {}".format(A))

x = np.array([0.2, -1.1])
print("Vector x:\n {}".format(x))

Matrix A:
 [[3.4 2.6]
 [2.1 4.5]]
Vector x:
 [ 0.2 -1.1]


We can compute the matrix-vector product $y = Ax$ by:

我们可以通过以下方式计算矩阵向量乘积$ y = Ax $：

In [29]:
y = A.dot(x)
print(y)

[-2.18 -4.53]


Matrix-matrix multiplication is performed similarly. Computing $C = AB$, where $A$, $B$, and $C$ are all matrices:

矩阵与矩阵乘法类似地。计算$ C = AB $，其中$ A $，$ B $和$ C $都是矩阵：

In [30]:
B = np.array([[1.3, 0], [0, 2.0]])

C = A.dot(B)
print(C)

[[4.42 5.2 ]
 [2.73 9.  ]]


The inverse of a matrix ($A^{-1}$) and the determinant ($\det(A)$) can be computed using functions in the NumPy submodule`linalg`:

可以使用 NumPy 子模块 `linalg` 中的函数计算矩阵的逆 ($A^{-1}$) 和行列式 ($\det(A)$)：

In [31]:
Ainv = np.linalg.inv(A)
print("Inverse of A:\n {}".format(Ainv))

Adet = np.linalg.det(A)
print("Determinant of A: {}".format(Adet))

Inverse of A:
 [[ 0.45731707 -0.26422764]
 [-0.21341463  0.34552846]]
Determinant of A: 9.839999999999998


> NumPy is large library, so it uses sub-modules to arrange functionality.

A very common matrix is the *identity matrix* $I$. We can create a $4 \times 4$ identity matrix using:

> NumPy 是大型库，因此它使用子模块来安排功能。

一个非常常见的矩阵是*单位矩阵* $I$。我们可以使用以下方法创建$4 \times 4$单位矩阵：

In [32]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**XUE.cn 练习题**：

- [编程题 ★★★ 将一个向量进行反转（第一个元素变为最后一个元素）](https://xue.cn/hub/app/exercise/1238)

- [编程题 ★★★ 创建一个 3x3 的矩阵，值域为 0 到 8](https://xue.cn/hub/app/exercise/1239)

- [编程题 ★★★ 创建一个 3x3 的单位矩阵](https://xue.cn/hub/app/exercise/1241)

- [编程题 ★★★ 创建一个 3x3x3 的随机数组](https://xue.cn/hub/app/exercise/1242)

- [编程题 ★★★ 创建一个 10x10 的随机数组，并找出该数组中的最大值与最小值](https://xue.cn/hub/app/exercise/1243)

- [编程题 ★★★ 创建一个长度为 30 的随机向量，并求它的平均值](https://xue.cn/hub/app/exercise/1244)

- [编程题 ★★★ 创建一个 2 维数组，该数组边界值为 1，内部的值为 0](https://xue.cn/hub/app/exercise/1245)

- [编程题 ★★★ 如何用 0 来填充一个数组的边界？](https://xue.cn/hub/app/exercise/1246)

- [编程题 ★★★ 创建一个 5x5 的矩阵，且设置值 1, 2, 3, 4 在其对角线下面一行](https://xue.cn/hub/app/exercise/1247)

## Array slicing

When working with arrays, it is often useful to extract subsets of an array. We might want just the first 3 entries of a long array, or we might want the second column of a 2D array (matrix). These operations are known as *array slicing* (https://en.wikipedia.org/wiki/Array_slicing).

We will explore slicing through examples. We start by creating an array filled with random values:

## 数组切片

使用数组时，提取数组的子集通常很有用。我们可能只需要长数组的前 3 个元素，或者我们可能需要 2D 数组（矩阵）的第二列。这些操作称为*数组切片*（https://en.wikipedia.org/wiki/Array_slicing）。

我们将通过实例探索切片。我们首先创建一个填充随机值的数组：

In [33]:
x = np.random.rand(5)
print(x)

[0.65273043 0.2217967  0.71295528 0.95785112 0.02222443]


Below are some slicing operations:

以下是一些切片操作：

In [34]:
## Using ':' implies the whole range of indices, i.e. from 0 -> (length-1)
y = x[:]
print("Slice using '[:]' {}".format(y))

## Using '1:3' implies indices 1 -> 3 (not including 3)
y = x[1:3]
print("Slice using '[1:3]': {}".format(y))

## Using '2:-1' implies indices 2 -> second-from-last
y = x[2:-1]
print("Slice using '[2:-1]': {}".format(y))

## Using '2:-2' implies indices 2 -> third-from-last
y = x[2:-2]
print("Slice using '[2:-2]': {}".format(y))

Slice using '[:]' [0.65273043 0.2217967  0.71295528 0.95785112 0.02222443]
Slice using '[1:3]': [0.2217967  0.71295528]
Slice using '[2:-1]': [0.71295528 0.95785112]
Slice using '[2:-2]': [0.71295528]


> Note the use of the index`-1`. The index`-1`corresponds to the last entry in the array, and`-2`the
> second last entry, etc. This is convenient if we know how far in from the end of an array a desired entry is.
> By using negative indices we can express this without reference to the length of the array.

> 注意索引 `-1` 的使用。索引 `-1` 对应于数组中的最后一个条目，`-2` 对应于第二个最后一个条目，以此类推。如果我们知道数组末尾到目标条目的距离是多少，这很方便。通过使用负索引，我们可以在不参考数组长度的情况下表达它。

If we want a slice to run from the start of an array, or to the end of an array, we do: 

如果我们想要从数组的开头或数组的末尾运行切片，我们会这样操作：

In [35]:
## Using ':3' implies start -> 3 (not including 3)
y = x[:3]
print("Slice using '[:3]': {}".format(y))

## Using '4:' implies 4 -> end
y = x[4:]
print("Slice using '[4:]': {}".format(y))

## Using ':' implies start -> end
y = x[:]
print("Slice using '[:]': {}".format(y))

Slice using '[:3]': [0.65273043 0.2217967  0.71295528]
Slice using '[4:]': [0.02222443]
Slice using '[:]': [0.65273043 0.2217967  0.71295528 0.95785112 0.02222443]


Slicing can be applied to 2D arrays:

切片可以用于二维数组：

In [36]:
B = np.array([[1.3, 0], [0, 2.0]])
print(B)

## Extract second row
r = B[1, :]
print(r)

[[1.3 0. ]
 [0.  2. ]]
[0. 2.]


There is more to array slicing syntax, for example it is possible to extract every 3rd entry. If you need to extract a sub-array, check first if you can do it using the compact array slicing syntax.

数组切片语法还有很多，例如可以提取每 3 个条目的第 3 个。如果需要提取子数组，请首先检查是否可以使用紧凑数组切片语法执行此操作。

**XUE.cn 练习题**：

- [编程题 ★★★ 如何获得昨天，今天和明天的日期 ?](https://xue.cn/hub/app/exercise/1255)

- [编程题 ★★★ 怎么获得所有与 2016 年 7 月的所有日期 ?](https://xue.cn/hub/app/exercise/1256)

- [编程题 ★★★ 如何计算 ((A+B)*(-A/2)) (不使用中间变量)?](https://xue.cn/hub/app/exercise/1257)

- [编程题 ★★★ 如何判断两随机数组相等](https://xue.cn/hub/app/exercise/1264)

- [编程题 ★★★ 创建一个大小为 10 的随机向量并且将该向量中最大的值替换为 0](https://xue.cn/hub/app/exercise/1267)

- [编程题 ★★★ 创建一个结构化数组，其中 x 和 y 坐标覆盖 [0, 1]x[1, 0] 区域](https://xue.cn/hub/app/exercise/1268)

- [编程题 ★★★ 如何通过滑动窗口计算一个数组的平均数 ?](https://xue.cn/hub/app/exercise/1297)

- [编程题 ★★★ 思考以为数组 Z，构建一个二维数组，其第一行是 (Z[0],Z[1],Z[2])，然后每一行移动一位，最后一行为 (Z[-3],Z[-2],Z[-1])](https://xue.cn/hub/app/exercise/1298)

## Exercises

Complete now the [07 Exercises](Exercises/07_Exercises.ipynb) notebook.

## 练习
现在完成 [练习 07](Exercises/07_Exercises.ipynb)