## Introduction

Object-oriented programming and design is an approach that is based around 'objects'.
You have already been working
regularly with objects such as lists, tuples, dictionaries, and NumPy arrays.

The topic of object-oriented programming is a whole lecture course on its own, so in this notebook
we will focus on:

- Classes
- Attributes of objects
- Class methods

We will do this primarily by example. We will not delve into inheritance and polymorphism.

Python supports the object-oriented programming paradigm; in fact, everything in Python is an object.
You have been using concepts from object-oriented computing throughout this course.

### Objectives

- Appreciate objects as instantiations of classes
- Understanding of attributes and methods of classes
- Learn to create simple classes
- Implement and use class methods

## 介绍

面向对象的编程和设计是一种基于 “对象” 的方法。
您已经熟悉使用过列表，元组，字典和 NumPy 数组等对象。

面向对象编程的主题是一个完整的讲座课程，所以在这堂课中
我们将重点关注：

- 类
- 对象的属性
- 类的方法

我们将主要通过示例来做到这一点。我们不会深入研究继承和多态。

Python 支持面向对象的编程范式; 事实上，Python 中的所有东西都是一个对象。
在本课程中，您一直在使用面向对象计算的概念。

### 目标

- 将对象视为类的实例化
- 理解类的属性和方法
- 学习创建简单的类
- 实现和使用类方法

We will be using NumPy, so we import it here:
我们将使用 NumPy，所以在此导入它

In [1]:
import numpy as np

## Example: Numpy array objects

Consider a NumPy array:

## 示例：Numpy 数组对象

考虑一个 NumPy 数组：

In [2]:
A = np.array([[1, -4, 7], [2, 6, -1]])
print(A)

[[ 1 -4  7]
 [ 2  6 -1]]


We already know how to check the type of an object:
我们已经知道如何检查对象的类型：

In [3]:
print(type(A))

<class 'numpy.ndarray'>


This says that`A`is an *instantiation* of the class`numpy.ndarray`. You can read this as '`A`is a`numpy.ndarray`'.

So what is a`numpy.ndarray`? It is a class that has *attributes* and *member functions*.

这表示 `A` 是类 `numpy.ndarray` 的*实例化*。您可以将其视为 “A” 是 “numpy.ndarray”。

什么是 `numpy.ndarray`？它是一个具有*属性*和*成员函数*的类。

### Attributes

Attributes are *data* that belong to an object. The array`A`has a number of attributes. An attribute we have seen already is`shape`:

### 属性

属性是属于对象的*数据*。数组 `A` 有许多属性。我们已经看到的属性是 `shape`：

In [4]:
s = A.shape
print(s)

(2, 3)


Every object of type`numpy.ndarray`has the attribute`shape`which describes the number of entries in the array in each direction. Other attributes are`size`, which is the total number of entries:

`numpy.ndarray` 类型的每个对象都有一个属性 `shape`，它描述了每个方向上数组中的项目数。其他属性是 `size`，这是项目的总数：

In [5]:
s = A.size
print(s)

6


and`ndim`, which is the number of array dimensions (i.e. 1 for a vector, 2 for a matrix):

还有 `ndim`，它是数组维数（例如：向量为 1，矩阵为 2）：

In [6]:
d = A.ndim
print(d)

2


Notice that after an attribute name there are no braces, i.e. no`()`. This is a feature of attributes - we are
just accessing some data that belongs to an object. We are not calling a function or doing any computational work.

请注意，在属性名称之后没有括号，即没有 `()`。这是属性的一个特征 - 我们是
只访问属于对象的一些数据。我们不是在调用函数或进行任何计算工作。

### Methods

Methods are *functions* that are associated with a class, and perform operations on the data associated with an instantiation of a class. A`numpy.ndarray`object has a method '`min`', which returns the minimum entry in
the array:

### 方法

方法是与类关联的*函数*，并对与类的实例化相关联的数据执行操作。`numpy.ndarray` 对象有一个方法'`min`'，它返回数组中的最小值：

In [7]:
print(A.min())

-4


Methods are functions, and as functions can take arguments. For example, we can use the method`sort`to sort the rows of an array:

方法是函数，函数可以带参数。例如，我们可以使用 `sort` 方法对数组的行进行排序：

In [8]:
A.sort(kind='quicksort')
print(A)

[[-4  1  7]
 [-1  2  6]]


where we have called the`sort`method that belongs to`numpy.ndarray`, and we have passed an argument that specifies that it should use quicksort.

我们调用属于 `numpy.ndarray` 的 `sort` 方法，并且我们传递了一个参数，指定它应该使用快速排序。

Object methods can take other objects as arguments. Given a two-dimensional array (matrix) $A$ and
a one-dimensional array (vector) $x$:

对象方法可以将其他对象作为参数。给定一个二维数组（矩阵）$A$和一维数组（向量）$x$：

In [9]:
A = np.array([[1, -4, 7], [2, 6, -1]])

x = np.ones(A.shape[1])
print(x)

[1. 1. 1.]


We can compute $b = Ax$ using the`dot`method:
我们可以使用 `dot` 方法计算$b = Ax$：

In [10]:
b = A.dot(x)
print(b)

[4. 7.]


## Finding class attributes and methods

Class attributes and methods are usually listed in documentation. For`numpy.ndarray`, all attributes and methods are listed and explained at http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html.

Using Jupyter (or IPython) you can use 'tab-completion' to see the available attributes and methods. You will often know from the name which one you need.

## 查找类属性和方法

类属性和方法通常列在文档中。对于 `numpy.ndarray`，所有属性和方法都在 <http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html> 中列出并解释。

使用 Jupyter（或 IPython），您可以使用'tab-补完'来查看可用的属性和方法。您通常会从名称中知道您需要哪一个。

**XUE.cn 练习题**：

- [选择题 ★ Python 使用什么关键字来定义类？](https://xue.cn/hub/app/exercise/627)

- [选择题 ★★ 类的基础知识 1](https://xue.cn/hub/app/exercise/145)

- [选择题 ★★ 类和子类的关系](https://xue.cn/hub/app/exercise/146)

- [选择题 ★★ 类的继承](https://xue.cn/hub/app/exercise/147)

- [选择题 ★★ "私有变量"的标示方法](https://xue.cn/hub/app/exercise/148)

- [选择题 ★★ 类的基础知识 2](https://xue.cn/hub/app/exercise/163)

- [选择题 ★★ 类的实例化和属性调用](https://xue.cn/hub/app/exercise/257)

## Creating classes

Sometimes we cannot find a class (object type) that suits our problem. In this case we can make our own.
As a simple example, consider a class that holds a person's surname and forename:

## 创建类

有时我们找不到适合我们问题的类（对象类型）。在这种情况下，我们可以自己做。
举一个简单的例子，考虑一个含有一个人的姓和名的类：

In [11]:
class PersonName:
    def __init__(self, surname, forename):
        self.surname = surname # Attribute
        self.forename = forename # Attribute

    # This is a method
    def full_name(self):
        "Return full name (forename surname)"
        return self.forename + " " + self.surname

    # This is a method
    def surname_forename(self, sep=","):
        "Return 'surname, forename', with option to specify separator"
        return self.surname + sep + " " + self.forename

Before dissecting the syntax of this class, we will use it.
We first create an object (an instantiation) of type`PersonName`:

在剖析这个类的语法之前，我们先来使用它。
我们首先创建一个类型为 `PersonName` 的对象（实例化）：

In [12]:
name_entry = PersonName("Bloggs", "Joanna")
print(type(name_entry))

<class '__main__.PersonName'>


We first test the attributes:

我们首先测试属性：

In [13]:
print(name_entry.surname)
print(name_entry.forename)

Bloggs
Joanna


Next, we test the class methods:

接下来，我们测试类的方法：

In [14]:
name = name_entry.full_name()
print(name)

name = name_entry.surname_forename()
print(name)

name = name_entry.surname_forename(";")
print(name)

Joanna Bloggs
Bloggs, Joanna
Bloggs; Joanna


Dissecting the class, it is declared by

In [ ]:
class PersonName:

We then have what is known as the *intialiser*:

In [ ]:
def __init__(self, surname, forename):
    self.surname = surname
    self.forename = forename

This is the 'function' that is called when we create an object, i.e. when we use`name_entry = PersonName("Bloggs", "Joanna")`. The keyword '`self`' refers to the object itself - it can take time to
develop an understanding of`self`. The initialiser in this case stores the surname and forename of the person (attributes). You can test when the initialiser is called by inserting a print statement.

This class has two methods:

In [ ]:
def full_name(self):
    "Return full name (forname surname)"
    return self.forename + " " + self.surname

def surname_forename(self, sep=","):
    "Return 'surname, forname', with option to specify separator"
    return self.surname + sep + " " + self.forename

These methods are functions that do something with the class data. In this case, from the forename and surname
they return the full name of the person, formatted in different ways.

解析这个类，它是由这一句声明的：

In [ ]:
class PersonName:

然后我们拥有所谓的 *初始化程序*：

In [ ]:
def __init__(self, surname, forename):
    self.surname = surname
    self.forename = forename

这是我们创建对象时调用的'函数'，即当我们使用 `name_entry = PersonName（“Bloggs”， “Joanna”）` 时。关键字 “self” 指的是对象本身 - 对 “self” 的理解可能需要时间。在这种情况下，初始化程序存储人员的姓氏和名字（属性）。您可以通过插入 print 语句来测试何时调用初始化程序。

In [ ]:
def full_name(self):
    "Return full name (forname surname)"
    return self.forename + " " + self.surname

def surname_forename(self, sep=","):
    "Return 'surname, forname', with option to specify separator"
    return self.surname + sep + " " + self.forename

这些方法是对类数据执行某些操作的函数。在这种情况下，从姓和名中返回人的全名，但格式不同。

**XUE.cn 练习题**：

- [编程题 ★★★★ 实现一个简单的打印城市信息的类](https://xue.cn/hub/app/exercise/58)

- [编程题 ★★★★★ 实现类 Point](https://xue.cn/hub/app/exercise/16)

- [编程题 ★★★★★ 实现类 Circle](https://xue.cn/hub/app/exercise/17)

## Operators

Operators like`+`,`-`,`*`and`/`are actually functions - in Python they are shorthand for functions with
the names`__add__`,`__sub__`,`__mul__`and`__truediv__`, respectively. By
adding these methods to a class, we can define what the mathematical operators should do.

## 运算符

像 `+`，`-`，`*` 和 `/` 这样的运算符实际上是函数 - 在 Python 中它们是以下这些函数的简写：分别为 `__add__`,`__sub__`,`__mul__` 和 `__truediv__`。通过将这些方法添加到类中，我们可以定义数学运算符应该做什么。

### Mixed-up maths

Say we want to create our own numbers with their own operations. As a simple (and very silly) example,
we decide we want to change notation such that '`*`' means division and '`/`' means multiplication.

To switch '`*`' and '`/`' for our special numbers, we create a class to represent our special numbers, and
provide it with its own`__mul__`and`__truediv__`functions.
We will also provide the method`__repr__(self)`- this is called when we use the`print`function.

### 混乱数学

假设我们想用自己的运算符创建的数字。作为一个简单（非常愚蠢）的例子，
我们决定改变符号，“*” 表示除法，“/” 表示乘法。

要为我们的特殊数字切换'`*`'和'`/`'，我们创建一个类来表示我们的特殊数字，和
为它提供自己的 `__mul__` 和 `__truediv__` 函数。
我们还将提供方法 `__repr__(self)`- 当我们使用 `print` 函数时调用它。

In [15]:
class crazynumber:
    "A crazy number class that switches the mutliplcation and division operations"

    # Initialiser
    def __init__(self, x):
        self.x = x # This is an attribute

    # Define multiplication (*) (this is a method)
    def __mul__(self, y):
        return crazynumber(self.x/y.x)

    # Define the division (/) (this is a method)
    def __truediv__(self, y):
        return crazynumber(self.x*y.x)

    # This is called when we use 'print' (this is a method)
    def __repr__(self):
        return str(self.x) # Convert type to a string and return

> *Note:* the method names`__mul__`,`__truediv__`,`__repr__`, etc, should not be called directly. They
> are mapped by Python to operators (`*`and`/`in the first two cases). The method`__repr__`is called behind the scenes when using`print`.

We now create two`crazynumber`objects:

> *注意：* 方法名称 `__mul__`,`__truediv__`,`__repr__` 等不应直接调用。他们
> 由 Python 映射到运算符（在前两种情况下为 `*` 和 `/`）。使用 `print` 时，在幕后调用 `__repr__` 方法。

我们现在创建两个 `crazynumber` 对象：

In [16]:
u = crazynumber(10)
v = crazynumber(2)

Since we have defined`*`to be division, we expect u\*v to be equal to 5:

因为我们已经将 `*` 定义为除法，所以我们期望 u\*v 等于 5：

In [17]:
a = u*v # This will call '__mul__(self, y)'
print(a) # This will call '__repr__(self)'

5.0


Testing '`/`':
测试'`/`':

In [18]:
b = u/v
print(b)

20


By providing methods, we have defined how the mathematical operators should be interpreted.

通过提供类的方法，我们已经重新定义了如何解释数学运算符。

**XUE.cn 练习题**：

- [判断题 ★★ 在 Python 中定义类时，运算符重载是通过重写特殊方法实现的](https://xue.cn/hub/app/exercise/972)

- [判断题 ★★ 定义类时实现了 eq() 方法，该类对象即可支持运算符==。这种说法正确吗？](https://xue.cn/hub/app/exercise/1004)

- [判断题 ★★ 定义类时实现了 pow() 方法，该类对象即可支持运算符**。这种说法正确吗？](https://xue.cn/hub/app/exercise/1005)

### Equality testing

We have previously used library versions of sorting functions, and seen that they are much faster than our own implementations. What if we have a list of our own objects that we want to sort? For example,
we might have a`StudentEntry`class, and then have a list with a`StudentEntry`object for each student.
The built-in sort functions cannot know how we want to sort our list.

Another case is if we have a list of numbers, and we we want to sort according to a custom rule?

The built-in sort functions do not care about the details of our data. All they rely on
are *comparisons*, e.g. the`<`,`>`, and`==`operators. If we equip our class with comparison operators,
we can use built-in sorting functions.

### 等价测试

我们以前使用过库版本的排序函数，并且看到它们比我们自己的实现快得多。如果我们有一个我们想要排序的自己的对象列表怎么办？例如，
我们可能有一个 `StudentEntry` 类，然后为每个学生提供一个带有 `StudentEntry` 对象的列表。
内置的排序函数无法知道我们如何对列表进行排序。

另一种情况是，如果我们有一个数字列表，我们想根据自定义规则进行排序？

内置排序功能不关心我们数据的细节。他们所依赖的只是*比较*，例如 `<`,`>`, 和 `==` 运算符。如果我们为我们的类配备比较操作符，
那么我们就可以使用内置的排序功能。

<font size=4 weight=600 >Custom sorting</font>

Say we want to sort a list of numbers such that all even numbers appear before odd numbers, but otherwise the usual ordering rule applies. We do not want to write our own sorting function. We can do this custom sorting by creating our own class for holding a number and equipping it with`<`,`>`, and`==`operators.
The functions corresponding to the operators are:

-`__lt__(self, other)`(less than`other`,`<`)
-`__gt__(self, other)`(greater than`other`,`>`)
-`__eq__(self, other)`(equal to`other`,`==`)

The functions return`True`or`False`.

<font size=4 weight=600 >自定义排序</font>

假设我们要对数字列表进行排序，使得所有偶数出现在奇数之前，否则适用通常的排序规则。我们不想编写自己的排序功能。我们可以通过创建自己的类来保存数字并使用 `<`，`>` 和 `==` 运算符进行自定义排序。
与运算符对应的函数是：

-`__lt __（self，other）`（小于 `other`，`<`）
-`__gt __（self，other）`（大于 `other`，`>`）
-`__eq __（self，other）`（等于 `other`，`==`）

函数返回 “True” 或 “False”。

Below is a class for storing a number which obeys our custom ordering rules:

下面是一个用于存储符合我们的自定义排序规则的数字的类：

In [19]:
class MyNumber:

    def __init__(self, x):
        self.x = x # Store value (attribute)

    # Custom '<' operator (method)
    def __lt__(self, other):
        if self.x % 2 == 0 and other.x % 2 != 0: # 我是偶数, other 是奇数, 所以我比较小
            return True
        elif self.x % 2 != 0 and other.x % 2 == 0: # 我是奇数, other 偶数, 所以我比较大
            return False
        else:
            return self.x < other.x # 使用常规的 “小于” 定义

    # Custom '==' operator (method)
    def __eq__(self, other):
        return self.x == other.x

    # Custom '>' operator (method)
    def __gt__(self, other):
        if self.x % 2 == 0 and other.x % 2 != 0: # I am even, other is odd, so I am not greater
            return False
        elif self.x % 2 != 0 and other.x % 2 == 0: # I am odd, other is even, so I am greater
            return True
        else:
            return self.x > other.x # Use usual ordering of numbers

    # This function is called by Python when we try to print something
    def __repr__(self):
        return str(self.x)

We can perform some simple tests on the operators (insert print statements into the methods if you want
to verify which function is called)

我们可以对运算符执行一些简单的测试（如果要验证调用哪个函数，则将 print 语句插入到方法中）

In [20]:
x = MyNumber(4)
y = MyNumber(3)
print(x < y) # Expect True (since x is even and y is odd)
print(y < x) # Expect False

True
False


We now try applying the built-in list sort function to check that the sorted list obeys our
custom sorting rule:

我们现在尝试应用内置列表排序功能来检查排序列表是否符合我们的自定义排序规则：

In [21]:
## Create an array of random integers
x = np.random.randint(0, 200, 10)

## Create a list of 'MyNumber' from x (using list comprehension)
y = [MyNumber(v) for v in x]

## This is the long-hand for building y
#y = []
#for v in x:
## y.append(MyNumber(v))

## Use the built-in list sort method to sort the list of 'MyNumber' objects
y.sort()
print(y)

[138, 138, 178, 19, 85, 89, 139, 139, 163, 181]


Without modifying the sort algorithm, we have applied our own ordering. Approaches like this are a feature of
object-oriented computing. The sort algorithms sort *objects*, and the objects simply need
the comparison operators. The sort algorithms do not need to know the details of the objects.

在不修改排序算法的情况下，我们应用了自己的排序。像这样的方法是面向对象计算的一个特征。排序算法排序*对象*，对象只需要比较运算符。排序算法不需要知道对象的细节。

## Using the magic methods

The special Python methods that begin and end with double underscore (`__`) are *magic* methods. They map to special operators, typically mathematical operators such as`*`,`/`,`<`,`==`, etc.

They are standard methods in that they can be called directly on an object, but this is not their intended use.
Use operators instead. Below is an example.

## 使用魔术方法

以双下划线（`__`）开头和结尾的特殊 Python 方法是 *magic* 方法。它们映射到特殊运算符，通常是数学运算符，如 `*`，`/`，`<`，`==` 等。

它们是标准方法，因为它们可以直接在对象上调用，但这不是它们的预期用法。
请改用运算符。以下是一个例子。

In [22]:
class SomePair:
    def __init__(self, x, y):
        self.x = x # Store value (attribute)
        self.y = y # Store value (attribute)

    # '==' operator (note that it has a return value)
    def __eq__(self, other):
        return self.x == other.x and self.y == other.y

a = SomePair(23, 2)
b = SomePair(23, 4)

## Check for equality using ==
print(a == b)

## Check for equality using __eq__ (not recommended)
print(a.__eq__(b))

False
False


An object does not need to have all the magic functions defined - just the ones you intend to use. If you try to use
and operator that is not defined you will get an error.

对象不需要定义所有魔术函数 - 只需要定义那些打算使用的。如果您尝试使用未定义的运算符，则会出现错误。

**XUE.cn 练习题**：

- [选择题 ★★ 在 Python 中，不论类的名字是什么，初始化类的实例，方法总是什么？](https://xue.cn/hub/app/exercise/816)

- [判断题 ★★ Python 类的构造函数是`__init__()`。这种说法正确吗？](https://xue.cn/hub/app/exercise/1069)

- [选择题 ★★★ 理解类实例的 `__dict__` 属性](https://xue.cn/hub/app/exercise/265)

## Exercises

Complete now the [12 Exercises](Exercises/12%20Exercises.ipynb) notebook.

## 练习
现在完成 [习题 12](Exercises/12%20Exercises.ipynb)